// Mock dishes แบบ key-value โดยใช้ _id เป็น key
const dishes = {
  dish_001: {
    _id: "dish_001",
    nameTh: "น้ำพริกอ่อง",
    nameEn: "Northern Thai Tomato Chili Dip",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "cooking_kit",
    dishType: "dip",
    description: "น้ำพริกมะเขือเทศเคี่ยวกับหมูสับจนเข้มข้น รสเปรี้ยวหวานอมเผ็ด หอมเครื่องแกงแบบล้านนา กินคู่ผักสดกรอบและแคบหมูได้อย่างลงตัว",
    history: "อาหารพื้นเมืองล้านนาที่ใช้มะเขือเทศและหมูสับเป็นตัวชูรส",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northern/ID001_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_002: {
    _id: "dish_002",
    nameTh: "ข้าวซอยไก่",
    nameEn: "Northern Thai Chicken Khao Soi",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "cooking_kit",
    dishType: "noodle",
    description: "บะหมี่เหนียวนุ่มในน้ำแกงกะทิสีทองเข้มข้น หอมเครื่องเทศและพริกแกง เสิร์ฟพร้อมน่องไก่นุ่ม เส้นกรอบ และเครื่องเคียงตัดรส",
    history: "เมนูเส้นล้านนาที่สะท้อนอิทธิพลการค้าระหว่างจีนฮ่อและพม่า",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northern/ID002_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_003: {
    _id: "dish_003",
    nameTh: "ลาบคั่วเมือง",
    nameEn: "Northern Spiced Larb",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "cooking_kit",
    dishType: "salad",
    description: "ลาบสุกแบบเมืองเหนือคลุกพริกลาบและเครื่องเทศคั่ว หอมมะแขว่นโดดเด่น รสเค็มเผ็ดซับซ้อน พร้อมกลิ่นสมุนไพรสดในทุกคำ",
    history: "ลาบเหนือแตกต่างจากลาบอีสานด้วยพริกลาบและการคั่วจนหอม",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northern/ID003_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_004: {
    _id: "dish_004",
    nameTh: "แกงฮังเล",
    nameEn: "Northern Hang Lay Curry",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "cooking_kit",
    dishType: "curry",
    description: "หมูเนื้อนุ่มเคี่ยวช้าในน้ำแกงเข้มข้นจนเครื่องซึมเข้าเนื้อ รสเค็ม เปรี้ยว และหวานกลมกล่อม หอมขิง กระเทียม และเครื่องเทศแบบล้านนา",
    history: "อาหารล้านนาที่ได้รับอิทธิพลจากพม่าและนิยมทำในงานบุญ",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northern/ID004_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_005: {
    _id: "dish_005",
    nameTh: "แกงขนุน",
    nameEn: "Young Jackfruit Curry",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "cooking_kit",
    dishType: "curry",
    description: "ขนุนอ่อนต้มจนนุ่มแล้วแกงกับพริกแกงพื้นเมือง รสเผ็ดเค็มกำลังดี หอมชะอม ใบชะพลู และสมุนไพรที่ให้รสบ้าน ๆ อบอุ่น",
    history: "เมนูมงคลของชาวเหนือ เชื่อว่าชื่อขนุนช่วยหนุนนำสิ่งดี",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northern/ID005_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_006: {
    _id: "dish_006",
    nameTh: "ข้าวแต๋น",
    nameEn: "Northern Crispy Rice Cracker",
    region: "northern",
    regionNameTh: "ภาคเหนือ",
    type: "dessert",
    dishType: "dessert",
    description: "ข้าวเหนียวนึ่งตากแห้งทอดจนพองกรอบ ราดน้ำอ้อยหอมหวานเป็นเส้นบาง ๆ เนื้อสัมผัสเบา กรอบเพลิน เหมาะกับชาและกาแฟ",
    history: "ภูมิปัญญาถนอมข้าวเหนียวนึ่งที่เหลือของชุมชนภาคเหนือ",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "พร้อมรับประทาน แนะนำให้เสิร์ฟเย็น",
    imageUrl: [
      new URL("./assets/northern/ID006_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 129,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_007: {
    _id: "dish_007",
    nameTh: "ข้าวปุ้นซาวน้ำปลาร้า",
    nameEn: "Isan Rice Noodles with Fermented Fish",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "cooking_kit",
    dishType: "noodle",
    description: "เส้นขนมจีนเหนียวนุ่มคลุกน้ำปลาร้าปรุงรสนัว หอมพริกและสมุนไพร เสิร์ฟกับผักสดหลากชนิด ให้รสเค็มเผ็ดและสดชื่นในจานเดียว",
    history: "อาหารกินง่ายของชาวอีสานที่เรียกเส้นขนมจีนว่าข้าวปุ้น",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northeastern/ID007_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_008: {
    _id: "dish_008",
    nameTh: "แกงอ่อม",
    nameEn: "Isan Herb Curry",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "cooking_kit",
    dishType: "curry",
    description: "แกงน้ำขลุกขลิกที่รวมเนื้อและผักตามฤดูกาลไว้เต็มหม้อ รสเค็มเผ็ดนัวจากปลาร้า หอมผักชีลาว ต้นหอม และสมุนไพรอีสาน",
    history: "แกงพื้นบ้านอีสานที่รวมผักตามฤดูกาลไว้ในหม้อเดียว",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northeastern/ID008_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_009: {
    _id: "dish_009",
    nameTh: "แกงหน่อไม้ใบย่านาง",
    nameEn: "Bamboo Shoot Curry with Yanang",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "cooking_kit",
    dishType: "curry",
    description: "หน่อไม้ต้มจนหมดรสขื่นในน้ำใบย่านางสีเขียวเข้ม ปรุงรสนัวด้วยปลาร้า เติมเห็ดและผักพื้นบ้าน ได้แกงหอมสมุนไพรที่กินกับข้าวเหนียวพอดี",
    history: "ภูมิปัญญาอีสานใช้ใบย่านางลดรสขื่นของหน่อไม้",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northeastern/ID009_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_010: {
    _id: "dish_010",
    nameTh: "ส้มตำไทย",
    nameEn: "Thai Green Papaya Salad",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "cooking_kit",
    dishType: "salad",
    description: "มะละกอดิบเส้นกรอบตำกับมะเขือเทศ ถั่วฝักยาว และถั่วลิสง ปรุงรสเปรี้ยวหวานเค็มอย่างสมดุล เผ็ดกำลังดีและหอมมะนาวสด",
    history: "เมนูตำมะละกอที่แพร่หลายและปรับรสให้กลมกล่อมแบบไทยกลาง",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northeastern/ID010_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_011: {
    _id: "dish_011",
    nameTh: "ต้มแซ่บกระดูกหมู",
    nameEn: "Spicy Isan Pork Rib Soup",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "cooking_kit",
    dishType: "soup",
    description: "กระดูกหมูเคี่ยวจนเนื้อนุ่มในน้ำซุปร้อนรสเปรี้ยวเผ็ดจัดจ้าน หอมข้าวคั่ว พริกแห้ง และสมุนไพรสด ซดคล่องคอและอุ่นท้อง",
    history: "ต้มพื้นบ้านอีสานที่เคี่ยวกระดูกหมูจนนุ่มแล้วปรุงรสจัดท้ายสุด",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/northeastern/ID011_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_012: {
    _id: "dish_012",
    nameTh: "ทับทิมกรอบ",
    nameEn: "Red Rubies in Coconut Milk",
    region: "northeastern",
    regionNameTh: "ภาคอีสาน",
    type: "dessert",
    dishType: "dessert",
    description: "แห้วเนื้อกรอบหั่นเต๋าเคลือบแป้งสีทับทิมเนื้อนุ่มหนึบ เสิร์ฟในน้ำกะทิหอมหวานมัน พร้อมน้ำแข็งบดเย็นชื่นใจ",
    history: "ขนมไทยคลายร้อนที่ได้ชื่อจากสีแดงคล้ายอัญมณีทับทิม",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "พร้อมรับประทาน แนะนำให้เสิร์ฟเย็น",
    imageUrl: [
      new URL("./assets/northeastern/ID012_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 129,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_013: {
    _id: "dish_013",
    nameTh: "แกงรัญจวน",
    nameEn: "Royal Thai Ranjuan Curry",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "cooking_kit",
    dishType: "curry",
    description: "เนื้อนุ่มในน้ำแกงใสที่หอมเอกลักษณ์จากน้ำพริกกะปิ ตะไคร้ และโหระพา รสเปรี้ยวเค็มกลมกล่อม มีความเผ็ดอ่อน ๆ ช่วยเรียกน้ำย่อย",
    history: "อาหารชาววังสมัยรัชกาลที่ 5 ที่นำของเหลือมาปรุงเป็นแกงใหม่",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/central/ID013_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_014: {
    _id: "dish_014",
    nameTh: "แกงเทโพหมูสามชั้น",
    nameEn: "Pork Belly Kang Thepho",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "cooking_kit",
    dishType: "curry",
    description: "หมูสามชั้นนุ่มมันพอดีเคี่ยวในแกงกะทิข้นกับผักบุ้งไทย รสเปรี้ยวหวานเค็มครบรส หอมใบมะกรูดและเครื่องแกงแบบไทยกลาง",
    history: "เดิมใช้ปลาเทโพ ก่อนปรับมาใช้หมูสามชั้นเมื่อปลาหายากขึ้น",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/central/ID014_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_015: {
    _id: "dish_015",
    nameTh: "มัสมั่นไก่",
    nameEn: "Chicken Massaman Curry",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "cooking_kit",
    dishType: "curry",
    description: "น่องไก่เคี่ยวจนเปื่อยนุ่มในแกงกะทิเนื้อข้น รสหวานเค็มละมุน หอมอบเชย ลูกกระวาน และเครื่องเทศ เสริมสัมผัสมันกรุบด้วยถั่วลิสง",
    history: "แกงไทยที่รับอิทธิพลอาหารมลายูและเครื่องเทศจากต่างแดน",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/central/ID015_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_016: {
    _id: "dish_016",
    nameTh: "แกงสิบหก",
    nameEn: "Sixteen-Ingredient Heritage Curry",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "cooking_kit",
    dishType: "curry",
    description: "แกงไทยโบราณที่อัดแน่นด้วยเครื่องเคราหลากชนิด รสเข้มข้นเป็นชั้น ๆ หอมพริกแกง สมุนไพร และเครื่องเทศที่เคี่ยวรวมกันอย่างพิถีพิถัน",
    history: "ตั้งชื่อตามจำนวนองค์ประกอบสำคัญในตำรับโบราณ",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/central/ID016_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_017: {
    _id: "dish_017",
    nameTh: "หมูชะมวง",
    nameEn: "Chanthaburi Pork with Cowa Leaves",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "cooking_kit",
    dishType: "curry",
    description: "หมูชิ้นโตเคี่ยวกับใบชะมวงจนเนื้อนุ่มและน้ำแกงงวดเข้าเนื้อ รสเปรี้ยวธรรมชาติผสานหวานเค็มอย่างกลมกล่อม หอมเครื่องแกงคั่ว",
    history: "อาหารท้องถิ่นขึ้นชื่อของจันทบุรีที่ใช้ใบชะมวงให้รสเปรี้ยว",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/central/ID017_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_018: {
    _id: "dish_018",
    nameTh: "ข้าวเหนียวมะม่วง",
    nameEn: "Mango Sticky Rice",
    region: "central",
    regionNameTh: "ภาคกลาง",
    type: "dessert",
    dishType: "dessert",
    description: "ข้าวเหนียวมูนเมล็ดสวยนุ่มหนึบ ซึมซับกะทิหอมมันกำลังดี เสิร์ฟกับมะม่วงสุกสีทองรสหวานฉ่ำและราดหัวกะทิเค็มอ่อน",
    history: "ขนมไทยที่จับคู่ผลไม้ฤดูร้อนกับภูมิปัญญาการมูนข้าวเหนียว",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "พร้อมรับประทาน แนะนำให้เสิร์ฟเย็น",
    imageUrl: [
      new URL("./assets/central/ID018_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 129,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_019: {
    _id: "dish_019",
    nameTh: "หน่อไม้หวานต้มกะทิ",
    nameEn: "Sweet Bamboo Shoot in Coconut Milk",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "cooking_kit",
    dishType: "curry",
    description: "หน่อไม้หวานเนื้อนุ่มต้มในน้ำกะทิสดรสหวานมันเค็มอ่อน เติมสะตอและชะอมให้กลิ่นพื้นถิ่นโดดเด่น เป็นแกงใต้รสนุ่มที่กินง่าย",
    history: "อาหารพื้นบ้านใต้ที่ใช้หน่อไม้ตามฤดูกาลจากสวน",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/southern/ID019_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_020: {
    _id: "dish_020",
    nameTh: "แกงระแวงเนื้อ",
    nameEn: "Beef Rawang Curry",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "cooking_kit",
    dishType: "curry",
    description: "เนื้อวัวเคี่ยวในแกงกะทิขลุกขลิกจนเครื่องเกาะชิ้นเนื้อ รสเข้มข้นคล้ายพะแนง แต่โดดเด่นด้วยกลิ่นขมิ้น ตะไคร้ และสมุนไพรสด",
    history: "แกงไทยโบราณที่มีเรื่องเล่าเชื่อมโยงกับอาหารชวา",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/southern/ID020_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_021: {
    _id: "dish_021",
    nameTh: "ผัดสะตอกะปิกุ้ง",
    nameEn: "Stir-fried Stink Beans with Shrimp",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "cooking_kit",
    dishType: "stir_fry",
    description: "สะตอเม็ดกรอบผัดไฟแรงกับกุ้งเนื้อเด้งและซอสกะปิเข้มข้น รสเค็มหวานเผ็ดถึงเครื่อง หอมพริกและกะปิแบบอาหารใต้แท้",
    history: "เมนูใต้ที่นำวัตถุดิบประจำถิ่นอย่างสะตอมาปรุงกับกะปิ",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/southern/ID021_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_022: {
    _id: "dish_022",
    nameTh: "ยำไตปลา",
    nameEn: "Spicy Fermented Fish Innards Salad",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "cooking_kit",
    dishType: "salad",
    description: "ไตปลารสเข้มคลุกกับเนื้อปลาทูย่างและสมุนไพรซอยนานาชนิด ปรุงรสเผ็ดเค็มเปรี้ยวจัดจ้าน หอมตะไคร้ ใบมะกรูด และพริกสด",
    history: "การประยุกต์ไตปลาหมักซึ่งเป็นภูมิปัญญาถนอมอาหารของภาคใต้",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/southern/ID022_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_023: {
    _id: "dish_023",
    nameTh: "ไก่กอและ",
    nameEn: "Southern Golek Chicken",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "cooking_kit",
    dishType: "grill",
    description: "ไก่หมักเนื้อนุ่มย่างพร้อมทาเครื่องแกงกะทิสีส้มแดงซ้ำหลายชั้น รสหวานเค็มเผ็ดอ่อน ๆ หอมเครื่องเทศและกลิ่นควันจากเตา",
    history: "อาหารมลายูปักษ์ใต้ที่นิยมในพื้นที่ชายแดนใต้",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/southern/ID023_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_024: {
    _id: "dish_024",
    nameTh: "สาคูต้นราดกะทิ",
    nameEn: "Palm Sago with Coconut Milk",
    region: "southern",
    regionNameTh: "ภาคใต้",
    type: "dessert",
    dishType: "dessert",
    description: "เม็ดสาคูต้นแท้ต้มจนใสและนุ่มหนึบเป็นธรรมชาติ ราดด้วยกะทิสดรสหวานมันตัดเค็มเล็กน้อย ให้รสละมุนและกลิ่นหอมแบบขนมพื้นบ้านใต้",
    history: "ขนมจากแป้งสาคูต้นแท้ซึ่งเป็นวัตถุดิบพื้นถิ่นภาคใต้",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "พร้อมรับประทาน แนะนำให้เสิร์ฟเย็น",
    imageUrl: [
      new URL("./assets/southern/ID024_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 129,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_025: {
    _id: "dish_025",
    nameTh: "สปาเกตตีผัดหอยลายน้ำพริกเผา",
    nameEn: "Spaghetti with Clams and Chili Jam",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "cooking_kit",
    dishType: "noodle",
    description: "เส้นสปาเกตตีเหนียวนุ่มผัดกับหอยลายเนื้อหวานและน้ำพริกเผา รสหวานเผ็ดเค็มกลมกล่อม หอมกระเทียมและใบโหระพาแบบไทย",
    history: "เมนูคาเฟ่ยุคใหม่ที่ผสานเส้นอิตาเลียนกับรสผัดไทย",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/fusion/ID025_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_026: {
    _id: "dish_026",
    nameTh: "เปาะเปี๊ยะสดผัดไทยเส้นชาร์โคล",
    nameEn: "Charcoal Pad Thai Fresh Rolls",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "cooking_kit",
    dishType: "fusion",
    description: "ผัดไทยเส้นชาร์โคลสีดำรสเข้มข้น ห่อในแผ่นเปาะเปี๊ยะสดพร้อมผักกรอบ จับกินสะดวกและได้ทั้งความนุ่ม หนึบ และสดชื่นในคำเดียว",
    history: "การรวมสตรีตฟู้ดสองเมนูให้ร่วมสมัยและมีสีสัน",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/fusion/ID026_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_027: {
    _id: "dish_027",
    nameTh: "มักกะโรนีต้มยำไข่ชีสทอดกรอบ",
    nameEn: "Tom Yum Macaroni with Crispy Cheese Egg",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "cooking_kit",
    dishType: "fusion",
    description: "มักกะโรนีคลุกซอสต้มยำรสเปรี้ยวเผ็ดหอมสมุนไพร เสิร์ฟกับไข่และชีสทอดจนด้านนอกกรอบ ด้านในนุ่มเยิ้ม เพิ่มความมันให้รสจัดลงตัว",
    history: "เมนูโมเดิร์นฟิวชั่นจากคาเฟ่และคอนเทนต์อาหารร่วมสมัย",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/fusion/ID027_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_028: {
    _id: "dish_028",
    nameTh: "เกี๊ยวซ่าราดหน้า",
    nameEn: "Gyoza with Thai Gravy",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "cooking_kit",
    dishType: "fusion",
    description: "เกี๊ยวซ่าทอดฐานกรอบไส้แน่น ราดน้ำราดหน้าหอมเต้าเจี้ยวเนื้อข้น พร้อมคะน้าและผักกรอบ เป็นการผสมรสไทยจีนที่ทั้งนุ่มและกรุบ",
    history: "ต่อยอดจากราดหน้าหมี่กรอบโดยใช้เกี๊ยวซ่าแทนเส้น",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/fusion/ID028_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603099541178-958866380649?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_029: {
    _id: "dish_029",
    nameTh: "ข้าวมันไก่",
    nameEn: "Hainanese Chicken Rice",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "cooking_kit",
    dishType: "rice",
    description: "ไก่ต้มเนื้อนุ่มฉ่ำเสิร์ฟบนข้าวหุงน้ำซุปที่หอมมันทุกเมล็ด กินคู่กับน้ำจิ้มเต้าเจี้ยวรสเปรี้ยวเผ็ดและซุปร้อนกลมกล่อม",
    history: "เมนูจากชาวไหหลำที่ถูกปรับรสจนเป็นอาหารยอดนิยมของไทย",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "อุ่นด้วยไฟกลางจนร้อนทั่วก่อนรับประทาน",
    imageUrl: [
      new URL("./assets/fusion/ID029_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548943487-a2e4f43b4850?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 189,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  dish_030: {
    _id: "dish_030",
    nameTh: "ขนมถ้วยใบเตยไข่หวาน",
    nameEn: "Pandan Coconut Cup with Sweet Egg",
    region: "fusion",
    regionNameTh: "ไทยฟิวชั่น",
    type: "dessert",
    dishType: "dessert",
    description: "ขนมถ้วยใบเตยเนื้อนุ่มละมุน หอมกะทิและใบเตยสด รสหวานมันตัดเค็มเล็กน้อย เสิร์ฟกับไข่หวานเนื้อนุ่มเพื่อเพิ่มรสและสัมผัสที่น่าสนใจ",
    history: "ขนมฟิวชั่นที่ต่อยอดขนมถ้วยไทยด้วยองค์ประกอบไข่หวาน",
    storageInstruction:
      "เก็บวัตถุดิบในตู้เย็นที่อุณหภูมิ 0–4°C และปรุงภายใน 2 วันหลังได้รับสินค้า",
    reheatingInstruction: "พร้อมรับประทาน แนะนำให้เสิร์ฟเย็น",
    imageUrl: [
      new URL("./assets/fusion/ID030_001.jpg", import.meta.url).href,
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1562607635-4608ff48a859?auto=format&fit=crop&w=1200&q=80",
    ],
    price: 129,
    recipe: [],
    cookingSteps: [],
    nutritionCache: [],
    servings: 2,
    version: 1,
    isActive: true,
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
};

export default dishes;
